version: "3.9"  # optional since v1.27.0
services:
  # ubuntu:
  #   build: ubuntu 
  #   container_name: ubuntu
  mysql:
    ports:
      - target: 3306
        host_ip: 127.0.0.1
        published: 23306
        protocol: tcp
        mode: host
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=quintor_pw
      - MYSQL_DATABASE=cddb_quintor
      - MYSQL_USER=cddb_quintor
      - MYSQL_PASSWORD=quintor_pw
    volumes:
      - .\data:/var/lib/mysql

    image: 'mysql:5.6'

  java-rest:
    container_name: cddb_backend
    build: ./backend
    ports:
      - "28080:8080"
    links:
      - "mysql"
    depends_on:
      - "mysql"


  angular-fe:
    build: ./frontend
    ports:
      - '20080:80'
    container_name: cddb_frontend
    links:
      - "java-rest:cddb_backend"
    depends_on:
      - "java-rest"
    image: 'angular-fe:1.0'

